# Generated by Django 3.2.4 on 2021-06-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=255)),
                ('units_owned', models.CharField(max_length=255)),
                ('ppu_buy', models.CharField(max_length=255)),
                ('ppu_sell', models.CharField(max_length=255)),
                ('current_profit', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'portfolio_personaldb',
            },
        ),
    ]
