# Generated by Django 3.2.4 on 2021-06-11 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfolio',
            table='portfolios',
        ),
    ]
