# Generated by Django 3.2.4 on 2021-06-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaldb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('item_id', models.IntegerField()),
                ('units_owned', models.IntegerField()),
                ('ppu_buy', models.FloatField()),
                ('ppu_sell', models.FloatField()),
                ('current_profit', models.FloatField()),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
